-- V49__Update_production_installation_table.sql
-- Add missing columns to production_installation table

ALTER TABLE production_installation
ADD COLUMN epd_received_date DATE NULL,
ADD COLUMN production_started BOOLEAN DEFAULT FALSE,
ADD COLUMN production_start_date DATE NULL,
ADD COLUMN estimated_production_completion DATE NULL,
ADD COLUMN actual_production_completion DATE NULL,
ADD COLUMN site_visit_date DATE NULL,
ADD COLUMN site_measurements_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN flooring_completion_date DATE NULL,
ADD COLUMN ceiling_completion_date DATE NULL,
ADD COLUMN electrical_work_completed BOOLEAN DEFAULT FALSE,
ADD COLUMN plumbing_work_completed BOOLEAN DEFAULT FALSE,
ADD COLUMN carcass_delivery_date DATE NULL,
ADD COLUMN countertop_delivery_date DATE NULL,
ADD COLUMN shutters_delivery_date DATE NULL,
ADD COLUMN accessories_at_site BOOLEAN DEFAULT FALSE,
ADD COLUMN accessories_delivery_date DATE NULL,
ADD COLUMN carcass_installation_date DATE NULL,
ADD COLUMN countertop_installation_date DATE NULL,
ADD COLUMN shutters_installation_date DATE NULL,
ADD COLUMN accessories_installed BOOLEAN DEFAULT FALSE,
ADD COLUMN accessories_installation_date DATE NULL,
ADD COLUMN appliances_received_date DATE NULL,
ADD COLUMN appliances_installation_date DATE NULL,
ADD COLUMN lights_installation_date DATE NULL,
ADD COLUMN final_cleaning_done BOOLEAN DEFAULT FALSE,
ADD COLUMN final_cleaning_date DATE NULL,
ADD COLUMN handover_date DATE NULL,
ADD COLUMN warranty_provided BOOLEAN DEFAULT FALSE,
ADD COLUMN warranty_document_path VARCHAR(255) NULL,
ADD COLUMN overall_status VARCHAR(50) DEFAULT 'NOT_STARTED',
ADD COLUMN project_manager_assigned VARCHAR(255) NULL,
ADD COLUMN installation_team_lead VARCHAR(255) NULL,
ADD COLUMN estimated_completion_date DATE NULL,
ADD COLUMN actual_completion_date DATE NULL,
ADD COLUMN installation_notes TEXT NULL,
ADD COLUMN quality_check_passed BOOLEAN DEFAULT FALSE,
ADD COLUMN quality_check_date DATE NULL,
ADD COLUMN quality_check_notes TEXT NULL,
ADD COLUMN created_by VARCHAR(255) NULL,
ADD COLUMN updated_by VARCHAR(255) NULL;
