server:
  port: 8080


spring:
  application:
    name: kitchen-crm-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/kitchen_crm?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:kitchen_crm}
    password: ${DB_PASSWORD:password123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  jwt:
    secret: ${JWT_SECRET:JWT_SECRET=aW52YWxpZGF0ZWRKV1RTZWNyZXRLZXlGb3JLaXRjaGVuQ1JNQXBwbGljYXRpb25TZWN1cml0eQ==}
    expiration: 86400000 # 24 hours

  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}

  margin:
    default-percentage: ${DEFAULT_MARGIN:15.0}

logging:
  level:
    com.kitchencrm: DEBUG
    org.springframework.security: DEBUG